config/routes.rb
Rails.application.routes.draw do

  root to: "map#index"
  get "/ping", to: "application#ping"

  scope ":webstore_id", constraints: { format: "html" } do

    scope "/account" do
      scope module: :account do
        get "/", to: redirect("https://my.buckybox.com/customer"), as: "customer_dashboard"
      end

      scope module: :session do
        get "/sign_in", action: "new", as: "customer_sign_in"
        post "/sign_in", action: "create", as: nil
        delete "/sign_out", action: "destroy", as: "customer_sign_out"
      end
    end

    get "/", to: "store#home", as: "webstore"
    get "/start_checkout/:product_id", to: "store#start_checkout", as: "start_checkout"

    scope module: :customise_order do
      get "/customise_order", action: "customise_order"
      post "/customise_order", action: "save_order_customisation"
    end

    scope module: :authentication do
      get "/authentication", action: "authentication"
      post "/authentication", action: "save_authentication"
    end

    scope module: :delivery_options do
      get "/delivery_options", action: "delivery_options"
      post "/delivery_options", action: "save_delivery_options"
    end

    scope module: :payment_options do
      get "/payment_options", action: "payment_options"
      post "/payment_options", action: "save_payment_options"
    end

    scope module: :completed do
      get "/completed", action: "completed"
    end
  end
end

app/models/checkout/delivery_options.rb
# frozen_string_literal: true

require_relative "../form"

class DeliveryOptions < Form
  attribute :delivery_service, Integer
  attribute :start_date,       Date
  attribute :frequency,        String
  attribute :days,             Hash[Integer => Integer]
  attribute :extra_frequency,  Boolean

  validates :delivery_service, :start_date, :frequency, presence: true
  validates :days, presence: true, if: -> { frequency != "single" }

  delegate :has_extras?, to: :cart, prefix: true

  def existing_delivery_service_id
    customer.delivery_service_id
  end

  def can_change_delivery_service?
    !existing_delivery_service_id
  end

  def delivery_services
    API.delivery_services
  end

  def delivery_service_list
    delivery_services.map { |delivery_service| delivery_service_list_item(delivery_service) } \
                     .unshift([I18n.t("delivery_options.select_delivery_service"), nil])
  end

  def single_delivery_service?
    delivery_services.one?
  end

  def single_delivery_service
    delivery_services.last
  end

  def order_frequencies
    [
      [I18n.t("delivery_options.order_frequencies.select"),      nil],
      [I18n.t("delivery_options.order_frequencies.weekly"),      :weekly],
      [I18n.t("delivery_options.order_frequencies.fortnightly"), :fortnightly],
      [I18n.t("delivery_options.order_frequencies.monthly"),     :monthly],
      [I18n.t("delivery_options.order_frequencies.single"),      :single],
    ]
  end

  def extra_frequencies
    [
      [I18n.t("delivery_options.extra_frequencies.always"), false],
      [I18n.t("delivery_options.extra_frequencies.once"),   true],
    ]
  end

  def to_h
    {
      delivery_service_id: delivery_service,
      start_date:          start_date,
      frequency:           frequency,
      days:                days,
      extra_frequency:     extra_frequency,
    }
  end

private

  def customer
    cart.customer
  end

  def delivery_service_list_item(delivery_service)
    [delivery_service.name_days_and_fee, delivery_service.id]
  end
end

app/controllers/delivery_options_controller.rb
# frozen_string_literal: true

class DeliveryOptionsController < CheckoutController
  def delivery_options
    delivery_options = DeliveryOptions.new(cart: current_cart)
    render "delivery_options", locals: {
      order: current_order,
      delivery_services: DeliveryServiceDecorator.decorate_collection(delivery_options.delivery_services),
      delivery_options: delivery_options,
    }
  end

  def save_delivery_options
    args = { cart: current_cart }.merge(params[:delivery_options])
    return if cart_expired?(args)
    delivery_options = DeliveryOptions.new(args)
    delivery_options.save ? successful_delivery_options : failed_delivery_options(delivery_options)
  end

private

  def successful_delivery_options
    redirect_to next_step
  end

  def failed_delivery_options(delivery_options)
    flash[:alert] = t("oops") << t("colon") <<
                    delivery_options.errors.full_messages.join(", ").downcase

    render "delivery_options", locals: {
      order: current_order,
      delivery_services: DeliveryServiceDecorator.decorate_collection(delivery_options.delivery_services),
      delivery_options: delivery_options,
    }
  end

  def next_step
    payment_options_path
  end
end

app/views/delivery_options/_delivery_service.html.haml
.row-fluid.delivery_service-schedule-inputs{ id: delivery_service.schedule_input_id }
  .span12
    -# = f.input :start_date, label: false, collection: form_object.start_dates(delivery_service), input_html: { class: 'schedule-start-date span12' }, include_blank: false, disabled: true
    -# NOTE: cannot use SimpleForm here, see https://github.com/plataformatec/simple_form/issues/1104
    .control-group.select.required.disabled.webstore_delivery_options_start_date
      .controls
        = select_tag "delivery_options[start_date]", options_for_select(delivery_service.start_dates), class: "select required disabled schedule-start-date span12"

    %h4= t('delivery_options.repeat_delivery')
    = f.input :frequency, label: false, collection: form_object.order_frequencies, input_html: { class: 'delivery_service-schedule-frequency span12' }, include_blank: false, disabled: true

    = f.simple_fields_for(:days) do |g|
      %table.order-days.table.table-bordered
        %tbody
          - delivery_service.dates_grid.each_with_index do |week, index|
            %tr
              %td= index.succ.ordinalize
              - week.each do |day, number|
                - day_en = I18n.t('date.abbr_day_names', locale: :en)[number % 7]
                %td= g.input "#{number}", label: day, input_html: { data: ({enabled: true} if delivery_service.public_send(day_en.downcase)) }, wrapper_html: { id: "day-#{number}" }, as: :boolean, disabled: true

app/views/delivery_options/delivery_options.html.haml
= render partial: 'order', object: order

= simple_form_for(delivery_options, url: delivery_options_path) do |f|
  = f.input :cart_id, as: :hidden

  #webstore-delivery_service.row-fluid.webstore-section{ style: "display: #{delivery_options.can_change_delivery_service? ? 'block' : 'none'}" }
    .span12
      .row-fluid
        .span12
          - if delivery_options.single_delivery_service?
            %h4= t("delivery_options.#{delivery_options.single_delivery_service.pickup_point ? 'pickup' : 'delivery'}_details")
          - else
            %h4= t 'delivery_options.pick_delivery_service'
      .row-fluid
        .span12
          - if delivery_options.single_delivery_service?
            = f.input :delivery_service, as: :hidden, input_html: { id: 'delivery_service_select', value: delivery_options.single_delivery_service.id}
            %strong= delivery_options.single_delivery_service.name
          - else
            = f.input :delivery_service, collection: delivery_options.delivery_service_list, selected: delivery_options.existing_delivery_service_id, label: t('delivery_options.select_best'), include_blank: false, input_html: { id: 'delivery_service_select', class: 'span12' }
      .row-fluid
        .span12
          - delivery_services.each do |delivery_service|
            .delivery_service-info.hide{ id: "delivery_service-info-#{delivery_service.id}" }= delivery_service.instructions

  #webstore-schedule.hide.row-fluid{ class: "#{delivery_options.can_change_delivery_service? ? '' : 'webstore-section'}" }
    .span12
      .row-fluid
        .span12
          .row-fluid
            .span12
              %h4= t 'delivery_options.when'
          = render partial: 'delivery_service', collection: delivery_services, locals: { f: f, form_object: delivery_options }

  - if delivery_options.cart_has_extras?
    #webstore-extras-frequency.row-fluid
      .span12
        .row-fluid
          .span12
            .row-fluid
              .span12
                %h4= t 'delivery_options.extra_frequency'
            .row-fluid
              .span12= f.input :extra_frequency, label: false, collection: delivery_options.extra_frequencies, include_blank: false, input_html: { class: 'span12' }

  .row-fluid.webstore-section
    .span12= f.button :submit, t('next'), class: 'pull-right btn btn-process'