config/routes.rb
Rails.application.routes.draw do

  root to: "map#index"
  get "/ping", to: "application#ping"

  scope ":webstore_id", constraints: { format: "html" } do

    scope "/account" do
      scope module: :account do
        get "/", to: redirect("https://my.buckybox.com/customer"), as: "customer_dashboard"
      end

      scope module: :session do
        get "/sign_in", action: "new", as: "customer_sign_in"
        post "/sign_in", action: "create", as: nil
        delete "/sign_out", action: "destroy", as: "customer_sign_out"
      end
    end

    get "/", to: "store#home", as: "webstore"
    get "/start_checkout/:product_id", to: "store#start_checkout", as: "start_checkout"

    scope module: :customise_order do
      get "/customise_order", action: "customise_order"
      post "/customise_order", action: "save_order_customisation"
    end

    scope module: :authentication do
      get "/authentication", action: "authentication"
      post "/authentication", action: "save_authentication"
    end

    scope module: :delivery_options do
      get "/delivery_options", action: "delivery_options"
      post "/delivery_options", action: "save_delivery_options"
    end

    scope module: :payment_options do
      get "/payment_options", action: "payment_options"
      post "/payment_options", action: "save_payment_options"
    end

    scope module: :completed do
      get "/completed", action: "completed"
    end
  end
end

app/models/checkout/payment_options.rb
# frozen_string_literal: true

require_relative "../form"

class PaymentOptions < Form
  PAID = "paid"

  attribute :name,            String
  attribute :phone_number,    String
  attribute :phone_type,      String
  attribute :address_1,       String
  attribute :address_2,       String
  attribute :suburb,          String
  attribute :city,            String
  attribute :postcode,        String
  attribute :delivery_note,   String
  attribute :payment_method,  String
  attribute :complete,        Boolean

  validates :name,           presence: true
  validates :phone_number,   presence: true, if: :require_phone
  validates :phone_type,     presence: true, if: :require_phone
  validates :address_1,      presence: true, if: :require_address_1
  validates :address_2,      presence: true, if: :require_address_2
  validates :suburb,         presence: true, if: :require_suburb
  validates :city,           presence: true, if: :require_city
  validates :postcode,       presence: true, if: :require_postcode
  validates :delivery_note,  presence: true, if: :require_delivery_note
  validates :payment_method, presence: true, if: :has_payment_options?

  attr_reader :address

  delegate :collect_phone, :require_phone, :collect_delivery_note, to: :webstore
  delegate :has_payment_options?, to: :cart
  delegate :address, to: :customer, prefix: true
  delegate :delivery_service, to: :order

  def name
    super || customer.name
  end

  def default_phone_number
    phone_number || address.default_phone_number
  end

  def default_phone_type
    phone_type || address.default_phone_type
  end

  def existing_customer?
    !customer.guest?
  end

  def phone_types(phone_collection_class = ::PhoneCollection)
    phone_collection_class.types_as_options
  end

  def pickup_point?
    delivery_service.pickup_point
  end

  def require_address_1
    !pickup_point? && webstore.require_address_1
  end

  def require_address_2
    !pickup_point? && webstore.require_address_2
  end

  def require_suburb
    !pickup_point? && webstore.require_suburb
  end

  def require_city
    !pickup_point? && webstore.require_city
  end

  def require_postcode
    !pickup_point? && webstore.require_postcode
  end

  def require_delivery_note
    !pickup_point? && webstore.require_delivery_note
  end

  # Returns whether the address is valid or not so we can hide the edit form when it is valid
  def address_complete?
    previous_errors = errors.dup

    begin
      valid? # populate `errors`
      (errors.keys - %i[phone_type payment_method]).empty?
    ensure
      # make sure we reset `errors` to its previous value for SimpleForm
      # kinda hackish but does the trick until we split up the models
      @errors = previous_errors
    end
  end

  def to_h
    {
      name:            name,
      phone_number:    phone_number,
      phone_type:      phone_type,
      address_1:       address_1,
      address_2:       address_2,
      suburb:          suburb,
      city:            city,
      postcode:        postcode,
      delivery_note:   delivery_note,
      payment_method:  payment_method,
      complete:        complete,
    }
  end

protected

  def before_standard_initialize(attributes)
    attributes = defaults.merge(attributes)
    @address_class = attributes.delete(:address_class)
  end

  def after_standard_initialize(_attributes)
    @address = build_address
  end

private

  attr_reader :address_class

  def defaults
    { address_class: ::Address }
  end

  def build_address
    address = if customer.existing_customer
      address_class.new(customer.existing_customer.address.to_h)
    else
      address_class.new
    end

    # forward address attributes
    address_class.address_attributes.each do |attribute|
      address_value = address.public_send(attribute)
      public_send("#{attribute}=", address_value) unless public_send(attribute)
      address.public_send("#{attribute}=", public_send(attribute))
    end

    # set phone number
    address.phone = { type: phone_type, number: phone_number }

    address
  end

  def cart
    super || BlackHole.new
  end

  def webstore
    cart.webstore
  end

  def customer
    cart.customer
  end

  def order
    cart.order
  end
end

app/controllers/payment_options_controller.rb
# frozen_string_literal: true

class PaymentOptionsController < CheckoutController
  def payment_options
    render "payment_options", locals: {
      order: current_order,
      payment_options: PaymentOptions.new(cart: current_cart),
      cart: current_cart,
    }
  end

  def save_payment_options
    args = { cart: current_cart }.merge(params[:payment_options])
    return if cart_expired?(args)
    payment_options = PaymentOptions.new(args)
    payment_options.save ? successful_payment_options : failed_payment_options(payment_options)
  end

private

  def successful_payment_options
    current_cart.run_factory
    # webstore_factory = current_cart.run_factory
    # customer_sign_in(webstore_factory.customer) # TODO: authenticate new customers here

    redirect_to next_step, notice: t("order_placed")
  end

  def failed_payment_options(payment_options)
    flash[:alert] = t("oops") << t("colon") <<
                    payment_options.errors.full_messages.join(", ").downcase

    render "payment_options", locals: {
      order: current_order,
      payment_options: payment_options,
      cart: current_cart,
    }
  end

  def next_step
    completed_path
  end
end

app/views/payment_options/payment_options.html.haml
= render partial: 'order', object: order

= simple_form_for(payment_options, url: payment_options_path) do |f|
  = f.input :cart_id, as: :hidden

  #webstore-address.row-fluid.webstore-section
    .span12
      - show_address_form = !payment_options.address_complete? || payment_options.pickup_point?

      #existing-address.row-fluid{ :class => ("hide" if show_address_form) }
        .span12
          .row-fluid
            .span12
              %h4= t 'payment_options.deliver_to'
          .row-fluid
            .span12
              = payment_options.address.to_s('<br>')
              %br
            = link_to t('payment_options.change_delivery_address'), 'javascript:void(0)', id: 'edit-address'
      #update-address.row-fluid{ :class => ("hide" unless show_address_form) }
        .span12
          .row-fluid
            .span12
              %h4= t 'payment_options.name'
          .row-fluid
            .span12= f.input :name, label: false, placeholder: t('payment_options.enter_name'), required: true, input_html: { class: 'span12' }

          - if payment_options.collect_phone
            .row-fluid
              .span12
                %h4= t 'payment_options.phone'
            .row-fluid
              .span9= f.input :phone_number, label: false, placeholder: t('payment_options.enter_phone'), required: payment_options.require_phone, input_html: { class: 'span12', value: payment_options.default_phone_number }
              .span3= f.input :phone_type, collection: payment_options.phone_types, label: false, required: payment_options.require_phone, include_blank: false, prompt: "", selected: payment_options.default_phone_type, input_html: { class: 'span12' }

          - unless payment_options.pickup_point?
            .row-fluid
              .span12
                %h4= t 'payment_options.deliver_to'
            .row-fluid
              .span12
                = f.input :address_1, label: false, placeholder: t('payment_options.address.address_1'), input_html: { class: 'span12', required: payment_options.require_address_1 }
                = f.input :address_2, label: false, placeholder: t('payment_options.address.address_2'), input_html: { class: 'span12', required: payment_options.require_address_2 }
                = f.input :suburb, label: false, placeholder: t('payment_options.address.suburb'), input_html: { class: 'span12', required: payment_options.require_suburb }
            .row-fluid
              .span9= f.input :city, label: false, placeholder: t('payment_options.address.city'), input_html: { class: 'span12' }, wrapper_html: { id: 'city', required: payment_options.require_city }
              .span3= f.input :postcode, label: false, placeholder: t('payment_options.address.postcode'), input_html: { class: 'span12', required: payment_options.require_postcode }, wrapper_html: { id: 'postal_code' }

            - if payment_options.collect_delivery_note
              .row-fluid
                .span12
                  %h4= t('payment_options.address.delivery_note')
              .row-fluid
                .span12
                  = f.input :delivery_note, as: :text, label: false, placeholder: t('payment_options.address.placeholders.delivery_note'), input_html: { class: 'span12', rows: 3, required: payment_options.require_delivery_note }

  - if cart.has_payment_options?
    - if payment_options.existing_customer?
      .row-fluid.webstore-section
        = render partial: 'payment_instructions', locals: { form_object: cart }

    .row-fluid.webstore-section
      #webstore-payment.span12
        .row-fluid
          #amount-due.span12.completed-header
            .row-fluid.important
              - if cart.negative_closing_balance?
                .span10= t 'payment_options.amount_due'
                .span2.text-right.total_price
                  = cart.amount_due
              - else
                .span10= t 'payment_options.in_credit'

        .row-fluid
          #payment-options.span12
            - if cart.negative_closing_balance?
              .row-fluid
                .form-horizontal.span6.center-row
                  = f.input :payment_method, as: :radio_buttons, collection: cart.payment_list, checked: payment_options.payment_method, label: t('payment_options.pay_by') << t('colon'), label_html: { class: 'emphasised-label' }
            - else
              .span12.text-center= t 'payment_options.no_payment'
              = f.input :payment_method, as: :hidden, input_html: { value: PaymentOptions::PAID }

  .row-fluid
    .span12.text-center
      = f.input :complete, as: :hidden, input_html: { value: true }
      = f.button :submit, t('payment_options.complete_order'), class: 'btn btn-process'