config/routes.rb
Rails.application.routes.draw do

  root to: "map#index"
  get "/ping", to: "application#ping"

  scope ":webstore_id", constraints: { format: "html" } do

    scope "/account" do
      scope module: :account do
        get "/", to: redirect("https://my.buckybox.com/customer"), as: "customer_dashboard"
      end

      scope module: :session do
        get "/sign_in", action: "new", as: "customer_sign_in"
        post "/sign_in", action: "create", as: nil
        delete "/sign_out", action: "destroy", as: "customer_sign_out"
      end
    end

    get "/", to: "store#home", as: "webstore"
    get "/start_checkout/:product_id", to: "store#start_checkout", as: "start_checkout"

    scope module: :customise_order do
      get "/customise_order", action: "customise_order"
      post "/customise_order", action: "save_order_customisation"
    end

    scope module: :authentication do
      get "/authentication", action: "authentication"
      post "/authentication", action: "save_authentication"
    end

    scope module: :delivery_options do
      get "/delivery_options", action: "delivery_options"
      post "/delivery_options", action: "save_delivery_options"
    end

    scope module: :payment_options do
      get "/payment_options", action: "payment_options"
      post "/payment_options", action: "save_payment_options"
    end

    scope module: :completed do
      get "/completed", action: "completed"
    end
  end
end

app/models/checkout/customise_order.rb
# frozen_string_literal: true

require_relative "../form"

class CustomiseOrder < Form
  attribute :has_customisations,  Boolean
  attribute :dislikes,            Array[Integer]
  attribute :likes,               Array[Integer]
  attribute :extras,              Hash[Integer => Integer]
  attribute :add_extra,           Boolean

  validate :validate_number_of_exclusions
  validate :validate_number_of_substitutions
  validate :validate_number_of_extras

  delegate :stock_list, to: :cart
  delegate :extras_list, to: :cart
  delegate :exclusions_limit, to: :product
  delegate :substitutions_limit, to: :product
  delegate :extras_limit, to: :product

  def exclusions?
    product.dislikes
  end

  def substitutions?
    product.likes
  end

  def extras_allowed?
    product.extras_allowed
  end

  def extras_unlimited?
    product.extras_unlimited
  end

  def exclusions_unlimited?
    product.exclusions_unlimited
  end

  def substitutions_unlimited?
    product.substitutions_unlimited
  end

  def to_h
    {
      dislikes:  dislikes,
      likes:     likes,
      extras:    extras,
    }
  end

protected

  def sanitize_attributes(attributes)
    attributes.fetch("dislikes", []).delete("")
    attributes.fetch("likes", []).delete("")
    attributes.fetch("extras", {}).delete_if do |_key, value|
      !value.to_i.between?(1, 1000)
    end

    attributes
  end

  def product
    cart.product
  end

  def exclusions_count
    dislikes.size || 0
  end

  def substitutions_count
    likes.size || 0
  end

  def extras_count
    extras.values.reduce(:+) || 0
  end

private

  def validate_number_of_exclusions
    validate_number_of(:exclusions)
  end

  def validate_number_of_substitutions
    validate_number_of(:substitutions)
  end

  def validate_number_of_extras
    validate_number_of(:extras)
  end

  def validate_number_of(items)
    items_count     = send("#{items}_count")
    items_unlimited = send("#{items}_unlimited?")
    items_limit     = send("#{items}_limit")

    return if items_unlimited || items_count <= items_limit

    errors.add(items, "you have too many #{items}, the maximum is #{items_limit}")
  end
end

app/controllers/customise_order_controller.rb
# frozen_string_literal: true

class CustomiseOrderController < CheckoutController
  def customise_order
    render "customise_order", locals: {
      order: current_order,
      customise_order: CustomiseOrder.new(cart: current_cart),
      extras_list: current_cart.extras_list,
    }
  end

  def save_order_customisation
    args = { cart: current_cart }.merge(params[:customise_order])
    return if cart_expired?(args)
    customise_order = CustomiseOrder.new(args)
    customise_order.save ? successful_order_customisation : failed_order_customisation(customise_order)
  end

private

  def successful_order_customisation
    redirect_to next_step
  end

  def next_step
    if current_webstore_customer.guest?
      authentication_path
    else
      delivery_options_path
    end
  end

  def failed_order_customisation(customise_order)
    flash[:alert] = t("oops") << t("colon") <<
                    customise_order.errors.values.join(", ").downcase

    render "customise_order", locals: {
      order: current_order,
      customise_order: customise_order,
      extras_list: current_cart.extras_list,
    }
  end
end

app/views/customise_order/_extra.html.haml
%tr.extras-row
  %td.information= extra.with_price_per_unit
  %td.cost.text-right= extra.formatted_price
  %td.quantity.text-right= g.input "#{extra.id}", input_html: { min: 0, value: 0, class: 'input-text span12' }, as: :integer, label: false

app/views/customise_order/customise_order.html.haml
= render partial: 'order', object: order

= simple_form_for(customise_order, url: customise_order_path, html: { class: 'form-inline' }) do |f|
  = f.input :cart_id, as: :hidden

  - if customise_order.exclusions?
    #webstore-customise.row-fluid.webstore-section
      .span12
        .row-fluid
          .span12= f.input :has_customisations, as: :boolean, label: t('customise_order.customise_product'), wrapper: :inline_checkbox, wrapper_html: { class: 'checkbox-header' }
        #webstore-customisations.row-fluid
          .span12
            .dislikes_input.clearfix
              = f.input :dislikes, label: "<i class='icon-minus-sign'></i>".html_safe, collection: customise_order.stock_list, input_html: { multiple: true, data: { placeholder: t('customise_order.exclude_items'), limits: customise_order.exclusions_limit} }, wrapper: :inline
            - if customise_order.substitutions?
              .likes_input.clearfix
                = f.input :likes, label:  "<i class='icon-plus-sign'></i>".html_safe, collection: customise_order.stock_list, input_html: { multiple: true, data: { placeholder: t('customise_order.substitute_with_items'), limits: customise_order.substitutions_limit} }, wrapper: :inline

  - if customise_order.extras_allowed?
    #webstore-extras.row-fluid.webstore-section
      .span12
        .row-fluid
          .span12
            %h4
              %i.icon-plus
              - if customise_order.extras_unlimited?
                = t 'customise_order.add_unlimited_extras'
              - else
                = t 'customise_order.add_n_extras', limit: customise_order.extras_limit

        .row-fluid
          .span12
            %table.table.table-bordered
              = f.simple_fields_for(:extras) do |g|
                %tbody
                  = render partial: 'extra', collection: extras_list, locals: { g: g }

            = f.input :add_extra, label: false, collection: extras_list, label_method: :with_price_per_unit, input_html: { class: 'span12' }

  .row-fluid.webstore-section
    .span12= f.button :submit, t('next'), class: 'pull-right btn btn-process'