config/routes.rb
Rails.application.routes.draw do

  root to: "map#index"
  get "/ping", to: "application#ping"

  scope ":webstore_id", constraints: { format: "html" } do

    scope "/account" do
      scope module: :account do
        get "/", to: redirect("https://my.buckybox.com/customer"), as: "customer_dashboard"
      end

      scope module: :session do
        get "/sign_in", action: "new", as: "customer_sign_in"
        post "/sign_in", action: "create", as: nil
        delete "/sign_out", action: "destroy", as: "customer_sign_out"
      end
    end

    get "/", to: "store#home", as: "webstore"
    get "/start_checkout/:product_id", to: "store#start_checkout", as: "start_checkout"

    scope module: :customise_order do
      get "/customise_order", action: "customise_order"
      post "/customise_order", action: "save_order_customisation"
    end

    scope module: :authentication do
      get "/authentication", action: "authentication"
      post "/authentication", action: "save_authentication"
    end

    scope module: :delivery_options do
      get "/delivery_options", action: "delivery_options"
      post "/delivery_options", action: "save_delivery_options"
    end

    scope module: :payment_options do
      get "/payment_options", action: "payment_options"
      post "/payment_options", action: "save_payment_options"
    end

    scope module: :completed do
      get "/completed", action: "completed"
    end
  end
end

app/views/layouts/_banner.html.haml
#bucky-box-controls.containter-fluid
  .container
    .row
      .span6
        = link_to root_path, title: "Bucky Box, easy-to-use software for your CSA, Vege Box Scheme, or Food Hub" do
          = image_tag "bucky-box-powered.png"

      #auth-controls.span6.text-right
        - if current_customer
          .btn-group
            = link_to "#{t('my_account')} (#{current_customer.name})", customer_dashboard_path, class: 'btn btn-inverse'
            = link_to '#', { class: 'btn btn-inverse dropdown-toggle', "data-toggle" => "dropdown" } do
              %span.caret
            .account-dropdown.dropdown-menu.pull-right
              .current-account.text-left
                %p
                  %strong= current_customer.webstore_id
                %p
                  = current_customer.name
                  %br
                  = current_customer.email
                %p.logout.text-right
                  = link_to t('log_out'), customer_sign_out_path, method: :delete

              - other_accounts = current_customers.reject { |customer| current_customer && customer.id == current_customer.id }
              - if other_accounts.any?
                .switch-accounts.text-left
                  %p
                    %strong Switch Accounts
                  - other_accounts.each do |customer|
                    %li
                      %i.icon-user.icon-white
                      = link_to customer_can_switch_account? ? webstore_url(customer.webstore_id) : 'javascript:alert("You cannot switch account now because you have an ongoing order.")' do
                        = customer.webstore_name

        - else
          = link_to t('log_in'), customer_sign_in_url(webstore_id: current_webstore.id)

#public-banner.containter-fluid
  .container
    .row
      = link_to webstore_path(current_webstore.id) do
        #company-logo.span12.text-center
          - if current_webstore.company_logo
            = image_tag(current_webstore.company_logo)
          - else
            %h1= current_webstore.name

app/views/layouts/_bugsnag.html.haml
- if (Rails.env.production? || Rails.env.staging?) && Figaro.env.bugsnag_api_key.present?
  / Bugsnag
  = javascript_include_tag "https://d2wy8f7a9ursnm.cloudfront.net/bugsnag-3.min.js", "data-apikey" => Figaro.env.bugsnag_api_key
  :javascript
    if (typeof Bugsnag !== 'undefined') {
      Bugsnag.beforeNotify = function(payload) {
        return (navigator.userAgent.match(/MSIE|Trident|Mobile|Googlebot/i) === null);
      }
    }

app/views/layouts/_common_head.html.haml
%meta{ charset: "utf-8" }
%meta{ name: "viewport", content: "width=device-width, initial-scale=1" }

= favicon_link_tag "/public/favicon.ico"
= favicon_link_tag "/public/apple-touch-icon.png", rel: "apple-touch-icon", type: "image/png"

= render partial: "layouts/bugsnag"
= render partial: 'layouts/pingdom'

app/views/layouts/_google_analytics.html.haml
- if Rails.env.production?
  - buckybox_tracker = defined?(ga_tracking_id) ? ga_tracking_id : Figaro.env.ga_tracking_id
  - webstore_tracker = defined?(current_webstore) && current_webstore.ga_tracking_id

  - if buckybox_tracker.present? || webstore_tracker.present?
    / Google Analytics
    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    - if buckybox_tracker.present?
      :javascript
        ga('create', '#{buckybox_tracker}', 'auto');
        ga('send', 'pageview');

    - if webstore_tracker.present?
      :javascript
        ga('create', '#{webstore_tracker}', 'auto', {'name': 'webstoreTracker'});
        ga('webstoreTracker.send', 'pageview');

app/views/layouts/_i18n.html.haml
:javascript
  // custom JS I18n helper - works like Rails' one
  I18n = {}

  I18n.translations = #{I18n.t('javascript').to_json.html_safe};

  I18n.t = function(key) {
    var current_scope = I18n.translations;
    $.each(key.split("."), function(i, key_part) {
      current_scope = current_scope[key_part];
        if (current_scope == undefined) {
          return false;
        }
    });
    return current_scope || "missing translation: #{I18n.locale}.javascript." + key;
  };

app/views/layouts/_pingdom.html.haml
- if (Rails.env.production? || Rails.env.staging?) && Figaro.env.pingdom_rum_id.present?
  / Pingdom
  :javascript
    try {
      var _prum = [['id', '#{Figaro.env.pingdom_rum_id}'],
                   ['mark', 'firstbyte', (new Date()).getTime()]];
      (function() {
          var s = document.getElementsByTagName('script')[0]
            , p = document.createElement('script');
          p.async = 'async';
          p.src = '//rum-static.pingdom.net/prum.min.js';
          s.parentNode.insertBefore(p, s);
      })();
    } catch(e) {
      // swallow errors, it isn't vital that this code runs
    }

app/views/layouts/application.html.haml
!!! 5

%html
  %head
    = render partial: "layouts/common_head"

    %title Bucky Box - #{t('web_store', webstore: current_webstore.name)}

    = csrf_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = render partial: 'layouts/google_analytics'
    = render partial: 'layouts/i18n'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true, async: true

  %body
    = render partial: 'layouts/banner'

    .container
      #customer-messages= render_flash_messages(flash)

      .row
        #content-information.span3
          #information
            = render partial: 'sidebar'
        #content-body.span9
          .row-fluid
            .span12= yield